/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Root */
		get: operations['root__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Health */
		get: operations['health_v1_health_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/parse_text': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Parse Text
		 * @description Parse a text and return a list of ingredients with quantities and eventual modifiers
		 */
		post: operations['parse_text_v1_parse_text_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/origins': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Origins
		 * @description Get the list of origins available in the database
		 *
		 *     Note: as the list is not too big, we let clients handle suggestions to users
		 */
		get: operations['get_origins_v1_origins_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/labels': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Labels
		 * @description Get the list of labels relevant for green-score computation
		 */
		get: operations['get_labels_v1_labels_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/ingredients': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Ingredients
		 * @description Get the list of ingredients relevant for green-score computation
		 */
		get: operations['get_ingredients_v1_ingredients_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/green-score': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Green Score
		 * @description Compute the green-score of a recipe given as a list of ingredients.
		 */
		post: operations['green_score_v1_green_score_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/**
		 * GreenScoreRequest
		 * @description Request body for the green-score computation endpoint.
		 *
		 *     It is a thin wrapper around a list of ingredients
		 */
		GreenScoreRequest: {
			/**
			 * Ingredients
			 * @description The ingredients of the recipe
			 */
			ingredients: components['schemas']['RecipeIngredientInput'][];
		};
		/**
		 * GreenScoreResponse
		 * @description Response model for the green-score computation endpoint.
		 */
		GreenScoreResponse: {
			/**
			 * Numericscore
			 * @description The computed green-score of the recipe, null if no ingredients have a score
			 */
			numericScore?: number | null;
			/**
			 * Lettergrade
			 * @description The letter grade corresponding to the numeric score, null if no ingredients have a score
			 */
			letterGrade?: string | null;
			/**
			 * Missingingredientids
			 * @description List of ingredient ids that were missing from the Agribalyse computation
			 * @default []
			 */
			missingIngredientIds: string[];
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components['schemas']['ValidationError'][];
		};
		/**
		 * Ingredient
		 * @description Ingredient model for Score My Recipe API
		 */
		Ingredient: {
			/**
			 * Id
			 * @description Taxonomy id of the item
			 */
			id: string;
			/**
			 * Label
			 * @description Name of the item
			 */
			label: string;
		};
		/**
		 * IngredientsResponse
		 * @description Response model for get_ingredients endpoint
		 */
		IngredientsResponse: {
			/** Ingredients */
			ingredients: components['schemas']['Ingredient'][];
		};
		/**
		 * Label
		 * @description Label model for Score My Recipe API
		 */
		Label: {
			/**
			 * Id
			 * @description Taxonomy id of the item
			 */
			id: string;
			/**
			 * Label
			 * @description Name of the item
			 */
			label: string;
		};
		/**
		 * LabelsResponse
		 * @description Response model for get_labels endpoint
		 */
		LabelsResponse: {
			/** Labels */
			labels: components['schemas']['Label'][];
		};
		/**
		 * Origin
		 * @description Origin model for Score My Recipe API
		 */
		Origin: {
			/**
			 * Id
			 * @description Taxonomy id of the item
			 */
			id: string;
			/**
			 * Label
			 * @description Name of the item
			 */
			label: string;
		};
		/**
		 * OriginsResponse
		 * @description Response model for get_origins endpoint
		 */
		OriginsResponse: {
			/** Origins */
			origins: components['schemas']['Origin'][];
		};
		/**
		 * RecipeIngredient
		 * @description Ingredient model for Score My Recipe API
		 */
		RecipeIngredient: {
			/** Taxonomy Id */
			taxonomy_id?: string | null;
			/** Is In Taxonomy */
			is_in_taxonomy: boolean;
			/** Codified Ingredient */
			codified_ingredient: string;
			/** Quantity G */
			quantity_g?: number | null;
		};
		/**
		 * RecipeIngredientInput
		 * @description A single ingredient of a recipe
		 */
		RecipeIngredientInput: {
			/**
			 * Id
			 * @description Unique identifier for the ingredient
			 */
			id: string;
			/**
			 * Name
			 * @description Display name of the ingredient
			 */
			name: string;
			/**
			 * Weight
			 * @description Weight in grams
			 */
			weight: number;
			/** @description Codified ingredient */
			codifiedIngredient: components['schemas']['TaxonomyItem'];
			/**
			 * Labels
			 * @description Labels / certifications (organic, fair-trade...)
			 * @default []
			 */
			labels: components['schemas']['TaxonomyItem'][];
			/**
			 * Seasonality
			 * @description Whether the ingredient is seasonal
			 * @default false
			 */
			seasonality: boolean;
			/** @description Origin country/region, null if unspecified */
			origin?: components['schemas']['TaxonomyItem'] | null;
		};
		/**
		 * RecipeParseRequest
		 * @description Request model for parse_text endpoint
		 */
		RecipeParseRequest: {
			/**
			 * Lang
			 * @description Language for the request (2 or 5 letter code)
			 */
			lang: string;
			/** Text */
			text: string;
		};
		/**
		 * RecipeParseResponse
		 * @description Response model for parse_text endpoint
		 */
		RecipeParseResponse: {
			/** Ingredients */
			ingredients: components['schemas']['RecipeIngredient'][];
		};
		/**
		 * TaxonomyItem
		 * @description A taxonomy reference with an id and a localized label.
		 *
		 *     Mirrors the frontend `TaxonomyItem` (used for codified ingredients, labels
		 *     and origins).
		 */
		TaxonomyItem: {
			/**
			 * Id
			 * @description Taxonomy identifier
			 */
			id: string;
			/**
			 * Label
			 * @description Display label in the current language
			 */
			label: string;
			/**
			 * Isintaxonomy
			 * @description Whether the item comes from the taxonomy (true) or is custom
			 */
			isInTaxonomy: boolean;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
			/** Input */
			input?: unknown;
			/** Context */
			ctx?: Record<string, never>;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	root__get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						[key: string]: unknown;
					};
				};
			};
		};
	};
	health_v1_health_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						[key: string]: unknown;
					};
				};
			};
		};
	};
	parse_text_v1_parse_text_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RecipeParseRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['RecipeParseResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_origins_v1_origins_get: {
		parameters: {
			query: {
				/** @description Language for the request (2 or 5 letter code) */
				lang: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['OriginsResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_labels_v1_labels_get: {
		parameters: {
			query: {
				/** @description Language for the request (2 or 5 letter code) */
				lang: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LabelsResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_ingredients_v1_ingredients_get: {
		parameters: {
			query: {
				/** @description Language for the request (2 or 5 letter code) */
				lang: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['IngredientsResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	green_score_v1_green_score_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['GreenScoreRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['GreenScoreResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
}
