/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/parse_text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Text
         * @description Parse a text and return a list of ingredients with quantities and eventual modifiers
         */
        post: operations["parse_text_v1_parse_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/origins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Origins
         * @description Get the list of origins available in the database
         *
         *     Note: as the list is not too big, we let clients handle suggestions to users
         */
        get: operations["get_origins_v1_origins_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Origin
         * @description Origin model for Score My Recipe API
         */
        Origin: {
            /**
             * Id
             * @description Taxonomy id of the origin
             */
            id: string;
            /**
             * Label
             * @description Name of the origin
             */
            label: string;
        };
        /**
         * OriginsResponse
         * @description Response model for get_origins endpoint
         */
        OriginsResponse: {
            /** Origins */
            origins: components["schemas"]["Origin"][];
        };
        /**
         * RecipeIngredient
         * @description Ingredient model for Score My Recipe API
         */
        RecipeIngredient: {
            /** Taxonomy Id */
            taxonomy_id?: string | null;
            /** Is In Taxonomy */
            is_in_taxonomy: boolean;
            /** Codified Ingredient */
            codified_ingredient: string;
            /** Quantity G */
            quantity_g?: number | null;
        };
        /**
         * RecipeParseRequest
         * @description Request model for parse_text endpoint
         */
        RecipeParseRequest: {
            /**
             * Lang
             * @description Language for the request (2 or 5 letter code)
             */
            lang: string;
            /** Text */
            text: string;
        };
        /**
         * RecipeParseResponse
         * @description Response model for parse_text endpoint
         */
        RecipeParseResponse: {
            /** Ingredients */
            ingredients: components["schemas"]["RecipeIngredient"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    parse_text_v1_parse_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeParseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_origins_v1_origins_get: {
        parameters: {
            query: {
                /** @description Language for the request (2 or 5 letter code) */
                lang: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OriginsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
